### ISSUE TITLE
Is it possible to use this model for regression, in addition to classification?

### ISSUE THREAD

**Issue by hw449** [jssong-lab/maxEnt#2]
Thank you very much for providing the community with such a powerful tool!
I am wondering whether your method can be applied to regression problems, such as binding affinity, or expression value? 

Best,
Hai

**Comment by afinneg2** [comment]
Hello Hai,

Thanks for your question. While I haven't tested the method for interpreting networks trained on regression problems, it should be applicable with very few modifications.  I assume you are primarily interested in syntax to create the layerSampler class and do interpretation for a regression model, is this correct?  If this is the case then, while I am busy today , I can provide an example in a few days. Would this be helpful or are you less interested in interpreting a specific network and more interested in general extension of the maxEnt method?

Best,
Alex

**Comment by hw449** [comment]
Thank you for your reply. I am interested in interpretation for a regression model. Please give me an example when it's convenient for you. Thank you very much!

**Comment by afinneg2** [comment]
Hello Hai,

To do interpretation for a feedforward network with regression output follow the example in examples/CTCF_covNet_example.ipynb and  make the following modifications:

```python
layer4Sampler =layerSampler(model ,
         layerIdx = 4,   ## replace with index of penultimate layer 
         beta = <your_tuned_beta> ,   
          mu = <your_tuned_mu> ,       
         outputUnitIdxs =(<index_of_regression_unit_in_output_layer>,) 
                                             )
```
Calling the layerSampler.sample method and generating plots should be exactly the same as in CTCF_covNet_example.ipynb. Thus, there is almost no change compared to CTCF_covNet_example.ipynb.  The resulting single nucleotide frequencies/motif plots should indicate the nucleotide patterns most important in determining the input to the regression layer of your network. 

I will update the example notebook to include applying the method to a regression task. For now, I hope this answers your question.

Best,
Alex

**Comment by hw449** [comment]
Thank you Alex for your help!   I'll try.

In my case I am training a network(with 2 convolution layers and 3 fully-connected layers) to predict the binding affinity of a TF to small DNA segments, with one-hot encoded DNA sequence as the input to the network.
You mentioned that "The resulting single nucleotide frequencies/motif plots should indicate the nucleotide patterns most important in determining the input to the regression layer of your network".

So my understanding is that the result do not reflect patterns most important in determining the final output (the binding affinity), but the output of the second convolution layer? 

Than you again.

Merry Christmas!

Hai

**Comment by afinneg2** [comment]
Hello Hai,

For your network,  if you set the layerIdx keyword argument to the index of the fully connected layer immediately preceding  the output (i.e. the penultimate layer) then interpretation output should indicate the patterns most important in determining the activations of this penultimate layer. In my previous comment by "regression layer"  I meant the layer whose units are linearly combined (with a bias) to generate the regression output at the last layer. Sorry for my previous sloppy language. 

P.S. About how small are your DNA segments?  If they are very small, it might make sense to use mu=0 corresponding to no a priori bias between G, C,A,T nucleotides?

Merry Christmas,
Alex

**Comment by hw449** [comment]
Thank you very much! This is very helpful.
Regards,
Hai
